import config from '../src/aws-exports'
import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import { Montserrat } from 'next/font/google';
import { Amplify, Auth } from 'aws-amplify';
import { AmplifyProvider, Authenticator, defaultDarkModeOverride, ThemeProvider } from "@aws-amplify/ui-react";
import Head from 'next/head'; 
import "@aws-amplify/ui-react/styles.css";


const montserrat = Montserrat({
  subsets: ['latin'] 
});

Amplify.configure({ ...config, ssr: false })
Auth.configure({...config});

export default function App({ Component, pageProps }: AppProps) {
  const theme = {
    name: 'my-theme',
    overrides: [defaultDarkModeOverride],
  };

  return (
    <>
      <Head>
        <title>Promptlio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className='debug-screens'>
          <AmplifyProvider>
            <Authenticator.Provider>
              <ThemeProvider theme={theme} colorMode="system">
                <Component {...pageProps} />
              </ThemeProvider>
            </Authenticator.Provider>
          </AmplifyProvider>
        </div>
      </main>
    </>
  );
}
